### ISSUE TITLE
TV accessory

### ISSUE THREAD

**Issue by sobeos** [hap-java/HAP-Java#81]
Are there plans to implement the TV accessory?

**Comment by ccutrer** [comment]
Not at this time. TVs are not documented in publicly available specifications, and presumably are actually part of AirPlay 2, not HomeKit (though there is a bit of a fuzzy line there, since AirPlay 2 may be using parts of HomeKit for pairing). See also https://github.com/mikebrady/shairport-sync/issues/535

**Comment by sobeos** [comment]
As far as I understand Apple's Homekit support has little to do with AirPlay 2.
Looks like KhaosT has implemented basic TV support in HAP-NodeJS:
[Commit](https://github.com/KhaosT/HAP-NodeJS/pull/638/commits/a3ab451a7c719fc48861223e88267bdc779722eb)
Reopen?

**Comment by ccutrer** [comment]
Interesting. I'm assuming he got his information by looking at protocol interactions with iOS 13 beta stuff, not from public docs. That (mostly) looks like vanilla HomeKit stuff.

And yes, HomeKit and AirPlay 2 are very interconnected. Apple TV's definitely are _not_ HomeKit devices (they're AirPlay 2), and yet they show up in Home app. But it looks like there is some TV support that's just vanilla HomeKit.

**Comment by iRayanKhan** [comment]
Hi, HAP doesn't need AirPlay 2 for the TV accessory.
The way it works is that the accessory only controls things like if its on or not like the toggle of it and the HDMI input. If the accessory relied on AirPlay 2, then it would be like the AppleTV or HomePod where it details if something is playing from the AirPlay 2 side which the TV doesn't. AirPort express for some reason adds due to AirPlay 2 in the Home App, but does absolutely nothing.

**Comment by dfrommi** [comment]
I was able to put together a TV accessory which in the end is using HAP-Java. It can't be directly copied to a PR, because I'm using a thin wrapper around HAP-Java for better integration into Kotlin and Project-Reactor, but end of the day, everything ends up at HAP-Java.

So if anyone is interested in migrating it to vanilla HAP-Java, [here it is](https://github.com/dfrommi/rehaktor/blob/master/samples/tv.main.kts). PR https://github.com/hap-java/HAP-Java/pull/110 is required for the linked input-source service.

**Comment by jannis6023** [comment]
Hi, any e.g. feature branch? Would really LOVE to use the TV Accessory for a new Integration!
