### ISSUE TITLE
Thermostat no longer working on iOS 13.x

### ISSUE THREAD

**Issue by amedeomantica** [hap-java/HAP-Java#86]
Hi, with iOS 13.x is no longer possible to set thermostat(s) temperature, I'm not sure if this is an iOS bug or something going wrong in the protocol.
Temperature set won't move from Zero. Current temperature is correctly reported

![image](https://user-images.githubusercontent.com/697450/65822693-aed18480-e248-11e9-9f8c-b063606fb0f1.png)

**Comment by yfre** [comment]
confirm. i have the same issue. but during this process - changing target temprature - there is not communication between home app and the server / java hap.
either something is missing /wrong in the thermostat description provided at the beginning by java hap or it is ios13 bug. 

@amedeomantica what do you use as server - openhab?

**Comment by sebasanblas** [comment]
Confirm too. I have the same issue.

**Comment by amedeomantica** [comment]
@yfre no, I run a Java Play framework app

**Comment by yfre** [comment]
reason found - ios13 expects the temperature unit  (celsius, fahrenheit) to be changeable but we had them read only.  i would say, pretty strange behaviour of ios13 home app, but anyway - it is right, according to HAP protocol the temperature unit is read & write.

pull request with the fix is created. there are not breaking API changes, so, drop-in replacement of hap jar should work

https://github.com/hap-java/HAP-Java/pull/87

**Comment by amedeomantica** [comment]
@yfre cool, I just tested your patch, it works! Thank you
