### ISSUE TITLE
Can something be learnt from the apple open source HomeKitADK?

### ISSUE THREAD

**Issue by grouchal** [hap-java/HAP-Java#97]
See here for more details:

https://github.com/apple/HomeKitADK

**Comment by ccutrer** [comment]
I’ve already been looking through it a bit yesterday. I think the short version is it’s a nice reference implementation, and there may be a few small things to learn from it, especially if we find ourselves in a state where things aren’t working again. But overall it’s not a massive revelation, since we already had the spec.
